### ISSUE TITLE
FITS image doesn't updated on Fits tab of Aux Monitor

### ISSUE THREAD

**Issue by gerhajdu** [astromg/TOI#6]
The first FITS image is loaded when the tab is selected, but it never updates to a different one.

**Comment by astromg** [comment]
Surprising. Just to be specific:

- [ ] You manually select FITS tab, before the end of the exposure.
- [ ] when the first exposure is finished, fits image is refreshed.
- [ ] with each next exposure the fits image is NOT refreshed

what happens when You don't touch fits tab ? (the tab should be brought up automatically after exposure is ready)

**Comment by astromg** [comment]
fixed by magic

**Comment by astromg** [comment]
fixed by magic
